["0.0-0.1.3"]
BinDeps = "0.0-0.6"

["0.0.3-0.0.8"]
MathProgBase = "0.1-0.2"

["0.0.3-0.0.9"]
julia = "0.2-0.6"

["0.0.9-0.0.19"]
MathProgBase = "0.3"

["0.0.10-0.0.19"]
julia = "0.3-0.6"

["0.0.11-0.0.19"]
Compat = "0.0-0.33"

["0.1"]
julia = "0.4-0.6"

["0.1.0-0.1.1"]
MathProgBase = "0.4"

["0.1.2-0.1.7"]
MathProgBase = "0.5"

["0.1.4-0.1.7"]
Compat = "0.8.6-0.33"

["0.2"]
julia = "0.5-0.6"
MathProgBase = "0.5-0.6"

["0.2.6-0.2.8"]
Compat = "0.18-0.33"
