["0.0"]
julia = "0.2"
Calendar = "0.1-0.4"

["0.4"]
julia = "0.5-0.7"

["0.4-0.5"]
MbedTLS = "0.4-0.5"

["0.4.0-0.4.1"]
Compat = "0.9.5-0.49"

["0.4.2-0.4.3"]
Compat = "0.17-0.49"

["0.5"]
julia = "0.6-0.7"

["0.5.5"]
Compat = "0.37-0.49"
