["0.0"]
julia = "0.1-0.7"

["0.0-0.2"]
Compat = "0.3.5-0.53"
Zlib = "0.1.7-0.1.12"

["0.0-0.2.1"]
LightXML = "0.1.10-0.6"

["0.1"]
julia = "0.3"

["0.2.0-0.2.1"]
julia = "0.1-0.7"

["0.2.2"]
julia = "0.3-0.7"

["0.2.2-0.3.2"]
LightXML = "0.2-0.6"

["0.3-0.5"]
julia = "0.4-0.7"

["0.3.0-0.3.2"]
Libz = "0.0-0.2"

["0.3.2"]
BufferedStreams = "0.0.3-0.3"

["0.3.3-0.4.3"]
BufferedStreams = "0.1.1-0.3"
Libz = "0.1.1-0.2"
LightXML = "0.2.1-0.6"

["0.3.6"]
Compat = "0.7.15-0.53"

["0.4.0-0.4.3"]
Compat = "0.8.4-0.53"

["0.4.4"]
Libz = "0.2"

["0.4.4-0.4.5"]
Compat = "0.9.4-0.53"

["0.4.4-0.6"]
BufferedStreams = "0.2-0.3"
LightXML = "0.4-0.6"

["0.4.5-0.6"]
Libz = "0.2.1-0.2.4"

["0.5.0"]
Compat = "0.9.5-0.53"

["0.5.1-0.6"]
Compat = "0.17-0.53"

["0.6"]
julia = "0.5-0.7"
