["0.0-0.3"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"

["0.2-0.3"]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

["0.3"]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
