["0.0"]
julia = "0.3-0.6"
Compat = "0.4-0.44"
MathProgBase = "0.3.8-0.3.19"

["0.1-0.2"]
julia = "0.4-0.6"

["0.1-0.2.1"]
MathProgBase = "0.4"

["0.2.2-0.2.3"]
MathProgBase = "0.5"

["0.3"]
julia = "0.5-0.6"

["0.3-0.4"]
MathProgBase = "0.5-0.7"

["0.4"]
julia = "0.6"
