["0.1"]
julia = "0.1-0.6"
DataFrames = "0.1-0.10"
Datetime = "0.1"

["0.1-0.3.4"]
TimeSeries = "0.0-0.11"

["0.1.1-0.1.5"]
DataArrays = "0.0-0.6"

["0.2.0"]
julia = "0.2-0.6"

["0.2.1-0.3.4"]
julia = "0.3-0.6"

["0.3.4"]
Reexport = "0.0-0.1"

["0.3.4-0.5"]
StatsBase = "0.1-0.19"

["0.3.5"]
julia = "0.3"
TimeSeries = "0.5.11"

["0.4"]
julia = "0.4"
TimeSeries = "0.6-0.11"

["0.5"]
julia = "0.5-0.6"
TimeSeries = "0.9-0.11"
