["0.0.1-0.0.3"]
julia = "0.1-0.6"

["0.0.4"]
julia = "0.2"

["0.0.5"]
julia = "0.3-0.6"

["0.1"]
julia = "0.4-0.6"

["0.1-0.2"]
Interpolations = "0.0-0.7"

["0.1.1-0.2"]
Requires = "0.1-0.4"

["0.1.5"]
Compat = "0.7.15-0.37"

["0.2"]
julia = "0.5-0.6"
