["0.2-0.4"]
FixedPointNumbers = "0.0-0.2"

["0.2.0"]
julia = "0.2-0.4"

["0.2.0-0.2.49"]
Color = "0.1-0.4"

["0.2.1-0.2.11"]
julia = "0.1-0.4"

["0.2.2-0.2.9"]
Grid = "0.1-0.4"

["0.2.10-0.2.24"]
Grid = "0.2.4-0.4"

["0.2.10-0.2.44"]
Cartesian = "0.1-0.3"

["0.2.12-0.2.48"]
julia = "0.2-0.4"

["0.2.18-0.4"]
Homebrew = "0.0-0.6"

["0.2.20-0.4"]
BinDeps = "0.0-0.8"

["0.2.24-0.2.26"]
Units = "0.2"

["0.2.24-0.6.0"]
Zlib = "0.1"

["0.2.27-0.11"]
SIUnits = "0.0-0.1"

["0.2.45-0.4.5"]
Cartesian = "0.2-0.3"

["0.2.49-0.2.50"]
julia = "0.2"

["0.2.50"]
Color = "0.2"

["0.3-0.4.40"]
Color = "0.1-0.4"

["0.3-0.4.47"]
julia = "0.3-0.4"

["0.4.24-0.4.35"]
Compat = "0.2.2-0.39"

["0.4.31-0.11"]
Graphics = "0.1-0.2"

["0.4.36-0.4.50"]
Compat = "0.4-0.39"

["0.4.41-0.4.43"]
Color = "0.4.7-0.4.8"

["0.4.44-0.4.50"]
Colors = "0.4-0.8"

["0.4.45-0.4.50"]
ColorVectorSpace = "0.0-0.5"

["0.4.48-0.4.50"]
julia = "0.3-0.6"

["0.5"]
julia = "0.4-0.6"
Colors = "0.6-0.8"
ColorVectorSpace = "0.1-0.5"
FixedPointNumbers = "0.1-0.2"

["0.5-0.11"]
FileIO = "0.0-0.6"

["0.5.5"]
Compat = "0.7.15-0.39"

["0.5.6-0.5.9"]
Compat = "0.8.4-0.39"

["0.5.6-0.10"]
StatsBase = "0.1-0.19"

["0.5.10-0.8"]
Compat = "0.9.1-0.39"

["0.6-0.10"]
julia = "0.5-0.6"

["0.6-0.11"]
AxisArrays = "0.0-0.2"
Colors = "0.7-0.8"
ColorVectorSpace = "0.2-0.5"
FixedPointNumbers = "0.3-0.4"
ImageAxes = "0.0-0.4"
ImageCore = "0.0-0.5"
ImageFiltering = "0.0-0.2"
ImageMetadata = "0.0-0.4"
IndirectArrays = "0.0-0.3"
MappedArrays = "0.0"
Reexport = "0.0"

["0.8-0.9"]
ImageTransformations = "0.0-0.4"

["0.9.0"]
Compat = "0.18-0.39"

["0.9.1-0.11"]
Compat = "0.19-0.39"

["0.10-0.11"]
ImageTransformations = "0.2.2-0.4"

["0.11"]
julia = "0.6"
Requires = "0.1-0.4"
StatsBase = "0.14-0.19"

["0.11.2-0.11.5"]
ImageMorphology = "0.0"
