["0.0"]
DiffEqBase = "1.7-2.10"

["0.0-0.1"]
julia = "0.6-0.7"
Distributions = "0.1-0.15"
MacroTools = "0.1-0.4"
Mamba = "0.3-0.11"
Stan = "0.0-3.0"
Turing = "0.0-0.4"

["0.1"]
DiffEqBase = "1.7-3.4"
