["0.0"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Mamba = "5424a776-8be3-5c5b-a13f-3551f69ba0e6"
Stan = "682df890-35be-576f-97d0-3d8c8b33a550"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
