["0.0-0.1"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"
JSON = "0.1-0.16"

["0.0.1-0.0.4"]
julia = "0.1-0.7"

["0.0.1-0.0.5"]
HTTPClient = "0.1-0.2"

["0.0.4-0.0.5"]
Compat = "0.0-0.53"

["0.0.5"]
julia = "0.3-0.7"

["0.0.6-0.1"]
julia = "0.6-0.7"
HTTP = "0.0-0.6"
