["0.0-1.1.0"]
DataStructures = "0.2-0.7"
Debug = "0.0-0.1"

["0.0-1.6"]
Compat = "0.0-0.39"

["0.0.1"]
julia = "0.1-0.6"

["0.0.2-1.7"]
julia = "0.3-0.6"

["1.2-1.7.1"]
AutoHashEquals = "0.0-0.1"

["1.7.0-1.7.8"]
Compat = "0.7.6-0.39"

["1.7.2-1.7.11"]
AutoHashEquals = "0.0.8-0.1"

["1.7.9-1.7.11"]
Compat = "0.7.12-0.39"
