["0.0"]
Compat = "0.0-0.39"
Requires = "0.1-0.4"

["0.0.1"]
julia = "0.1-0.6"
Docile = "0.0-0.5"
ValidatedNumerics = "0.0.3-0.9"

["0.0.3"]
julia = "0.3-0.6"

["0.0.3-0.2"]
ValidatedNumerics = "0.1-0.9"

["0.1"]
Plots = "0.5.0"

["0.1-0.3"]
julia = "0.4-0.6"

["0.2"]
Compat = "0.0-0.39"

["0.2-0.3"]
RecipesBase = "0.0.6-0.2"

["0.3"]
Compat = "0.8.6-0.39"
ForwardDiff = "0.3-0.7"
ValidatedNumerics = "0.5-0.9"
