["0.0-0.1"]
OrdinaryDiffEq = "2.11-2.37"

["0.0-0.3"]
DiffEqBase = "1.15-2.10"

["0.0-1.0"]
julia = "0.6-0.7"
ForwardDiff = "0.5-0.7"
RecursiveArrayTools = "0.0-0.14"
Reexport = "0.0-0.1"
StaticArrays = "0.0-0.6"

["0.1-1.0"]
RecipesBase = "0.0-0.3"

["0.2-0.3"]
OrdinaryDiffEq = "2.33-2.37"

["1.0"]
DiffEqBase = "3.0-3.4"
OrdinaryDiffEq = "3.0-3.1"
