## Documentation: http://docs.travis-ci.com/user/languages/julia/

if: type != push

language: julia
os:
  - linux
julia:
  - "1.3"
  - "1"
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
before_script: .ci/travis_before_script.sh
script:
- julia --project=.ci/ --color=yes -e 'import RegistryCI; RegistryCI.test()'
- exit 1
branches:
  only:
    - master
notifications:
  email: false
git:
  depth: 99999999
