## Documentation: http://docs.travis-ci.com/user/languages/julia/

if: type != push

language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
  - 1.3
  # - nightly
# matrix:
#   allow_failures:
#     - julia: nightly
before_script: julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaRegistries/RegistryCI.jl", rev="0a818a7"))'
script: julia --color=yes -e 'import RegistryCI; RegistryCI.test()'
after_success:
  # - exit 0 # Administrators: uncomment this line to disable all automerging
  - if [ "$TRAVIS_JULIA_VERSION" != "1.2" ]; then exit; fi
  - julia -e 'ENV["JULIA_DEBUG"] = "RegistryCI,AutoMerge"; using RegistryCI; using Dates; RegistryCI.AutoMerge.travis(merge_new_packages=true, merge_new_versions=true, new_package_waiting_period=Minute(4320), new_version_waiting_period=Minute(20), registry="JuliaRegistries/General", authorized_authors=["JuliaRegistrator"])'
branches:
  only:
    - master
notifications:
  email: false
git:
  depth: 99999999
