["0.2.0-0.2.3"]
julia = "0.2-0.4"

["0.2.4-0.2.6"]
julia = "0.2-0.7"

["0.2.7-0.2.8"]
julia = "0.2-0.3"

["0.2.9"]
julia = "0.3"

["0.2.10-0.2.15"]
julia = "0.2-0.3"

["0.3.0-0.3.6"]
julia = "0.3"

["0.3.6-0.3.12"]
Compat = "0.0-0.53"

["0.3.7-0.3.12"]
julia = "0.3-0.4"

["0.3.7-0.3.14"]
Docile = "0.0-0.5"

["0.3.13-0.3.14"]
julia = "0.3-0.5"
Compat = "0.7.1-0.53"

["0.4.0-0.4.2"]
julia = "0.4-0.5"

["0.4.3"]
julia = "0.4"

["0.4.4-0.5.1"]
julia = "0.4-0.5"

["0.4.6"]
Compat = "0.8.5-0.53"

["0.5.0-0.5.2"]
Compat = "0.9.4-0.53"

["0.5.2-0.5.3"]
julia = "0.4-0.6"

["0.5.3-0.6"]
Compat = "0.17-0.53"

["0.6"]
julia = "0.5-0.6"

["0.7.0-0.7.2"]
julia = "0.6"

["0.7.3"]
Compat = "0.39-0.53"

["0.7.3-0.7.4"]
julia = "0.6-0.7"

["0.7.4"]
Compat = "0.41-0.53"
