["0.1"]
julia = "0.1-0.7"

["0.1-0.2"]
HDF5 = "0.1-0.8"

["0.1-0.4"]
NFFT = "0.0-0.2"
OIFITS = "0.1-0.3"
OptimPack = "0.1-0.3"

["0.1.0"]
Wavelets = "0.2"

["0.1.1-0.4"]
Wavelets = "0.1-0.6"

["0.2"]
julia = "0.3-0.7"

["0.2-0.4"]
JLD = "0.5-0.8"

["0.3"]
julia = "0.4-0.7"

["0.4"]
julia = "0.5-0.7"
