["0.1"]
julia = "0.4-0.7"

["0.1-0.3"]
Hiccup = "0.0-0.1"
MacroTools = "0.1-0.4"
Media = "0.1-0.3"

["0.2.0-0.2.1"]
julia = "0.5-0.7"

["0.2.2-0.2.5"]
julia = "0.4-0.7"

["0.2.6"]
julia = "0.4-0.5"

["0.2.7"]
julia = "0.4-0.7"

["0.3"]
julia = "0.6-0.7"
