["0.1-0.3"]
CxxWrap = "0.1.0-0.1.5"

["0.1-0.4"]
julia = "0.4"

["0.4-0.5.2"]
CxxWrap = "0.1.6"

["0.4.1-0.5.0"]
BinDeps = "0.0-0.6"
Compat = "0.0-0.31"

["0.5-0.7"]
julia = "0.5-0.6"

["0.5.1"]
Compat = "0.9.2-0.31"

["0.5.1-0.7"]
BinDeps = "0.4.5-0.6"

["0.5.2-0.7"]
Compat = "0.8-0.31"

["0.5.3-0.5.5"]
CxxWrap = "0.1.7-0.2"

["0.6"]
CxxWrap = "0.3"

["0.7"]
CxxWrap = "0.4.1"
