["0.1"]
julia = "0.2-0.3"

["0.1.0"]
DataFrames = "0.2-0.10"

["0.1.1-0.1.6"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"

["0.1.2-0.4"]
BinDeps = "0.0-0.6"

["0.1.3-0.4"]
Homebrew = "0.0-0.5"
WinRPM = "0.1-0.2"

["0.2.0-0.2.1"]
julia = "0.3"

["0.2.1-0.3.1"]
Compat = "0.0-0.31"

["0.2.2-0.3.0"]
julia = "0.4-0.6"

["0.2.2-0.3.1"]
CSV = "0.0-0.1"

["0.2.2-0.3.3"]
DataStreams = "0.0.1-0.0.12"
NullableArrays = "0.0-0.1"

["0.3.1-0.3.7"]
julia = "0.4.1-0.6"

["0.3.2-0.3.3"]
CSV = "0.0.8-0.1"
WeakRefStrings = "0.1-0.3"

["0.3.2-0.4"]
DataFrames = "0.1-0.10"

["0.3.4"]
DataStreams = "0.0.9-0.0.12"

["0.3.4-0.4"]
LegacyStrings = "0.1-0.2"
WeakRefStrings = "0.1.3-0.3"

["0.3.5"]
DataStreams = "0.0.10-0.0.12"

["0.3.6"]
DataStreams = "0.0.12"

["0.3.7"]
DataStreams = "0.0.13-0.1"

["0.4"]
julia = "0.5-0.6"
DataStreams = "0.1"

["0.4.5"]
Compat = "0.9.5-0.31"
