["0.1-0.9.8"]
julia = "0.1-0.6"

["0.9.9-0.14"]
julia = "0.3-0.6"

["0.9.15-0.12"]
Compat = "0.4-0.39"

["0.13-0.19"]
Compat = "0.8-0.39"

["0.15-0.19"]
julia = "0.4-0.6"

["0.20-0.24"]
julia = "0.5-0.6"
