["0.0"]
julia = "0.4-0.7"
AWSCore = "0.0-0.3"

["0.1"]
AWSCore = "0.1-0.3"
Nettle = "0.1-0.3"

["0.1-0.2"]
julia = "0.5-0.7"
URIParser = "0.0-0.3"

["0.1-0.3"]
Retry = "0.0-0.1"

["0.1.1-0.1.3"]
SymDict = "0.0-0.1"

["0.1.4-0.3"]
SymDict = "0.1.2-0.1.3"

["0.2"]
AWSCore = "0.2-0.3"

["0.2-0.3"]
MbedTLS = "0.1-0.5"

["0.3"]
julia = "0.6-0.7"
AWSCore = "0.3"
HTTP = "0.5.4-0.5.7"
