["0.0-0.1.0"]
DiffEqBase = "0.0-0.4"
FiniteElementDiffEq = "0.0-0.5"
OrdinaryDiffEq = "0.0-3.0"
RecursiveArrayTools = "0.0-0.3"
StochasticDiffEq = "0.0-3.0"

["0.0-0.8"]
julia = "0.5-0.7"

["0.0-1.0"]
RecipesBase = "0.1-0.3"

["0.1.1"]
DiffEqBase = "0.1.3-0.4"
OrdinaryDiffEq = "0.1.1-3.0"
StochasticDiffEq = "0.0.5-3.0"

["0.1.1-0.2.0"]
FiniteElementDiffEq = "0.0.5-0.5"

["0.1.1-0.3"]
RecursiveArrayTools = "0.0.2-0.3"

["0.2.0"]
DiffEqBase = "0.2-0.4"

["0.2.1-0.3"]
DiffEqBase = "0.3-0.4"

["0.4-0.5"]
DiffEqBase = "0.4"

["0.4-0.7"]
RecursiveArrayTools = "0.1.2-0.3"

["0.5-0.11"]
DiffEqPDEBase = "0.0-0.4"

["0.6"]
DiffEqBase = "0.5-0.14"

["0.7"]
DiffEqBase = "0.15"

["0.8"]
DiffEqBase = "1.0-2.10"

["0.8-1.0"]
RecursiveArrayTools = "0.4-0.14"

["0.9-0.11"]
DiffEqBase = "1.12-2.10"

["0.9-1.0"]
julia = "0.6-0.7"
DiffEqMonteCarlo = "0.0-0.10"
DiffEqNoiseProcess = "0.0-1.0"

["0.10-1.0"]
Juno = "0.1-0.4"

["1.0"]
DiffEqBase = "3.0-3.2"
DiffEqPDEBase = "0.4"
