["0.0-0.1"]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

["0.0-0.2.0"]
FiniteElementDiffEq = "794876cc-7f88-5b71-9fa9-be3737d389f3"

["0.0-0.11"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

["0.5-0.11"]
DiffEqPDEBase = "34035eb4-37db-58ae-b003-a3202c898701"

["0.9-0.11"]
DiffEqMonteCarlo = "78ddff82-25fc-5f2b-89aa-309469cbf16f"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"

["0.10-0.11"]
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
