["0.0"]
julia = "0.4-0.7"
AWSCore = "0.0-0.3"

["0.0.9"]
Compat = "0.0-0.53"

["0.1"]
AWSCore = "0.1-0.3"
Nettle = "0.1-0.3"

["0.1-0.2"]
julia = "0.5-0.7"
HttpCommon = "0.0-0.4"
Requests = "0.0-0.5"

["0.1-0.3"]
LightXML = "0.1-0.5"
Retry = "0.0-0.2"
SymDict = "0.0-0.1"
XMLDict = "0.0-0.1"

["0.2"]
AWSCore = "0.2-0.3"
URIParser = "0.0-0.3"

["0.2-0.3"]
DataStructures = "0.2-0.7"
MbedTLS = "0.1-0.5"

["0.3"]
julia = "0.6-0.7"
AWSCore = "0.3"
HTTP = "0.5.4-0.6"
