["0.0.1"]
julia = "0.1-0.6"

["0.0.2"]
julia = "0.2-0.6"
FactCheck = "0.0-0.4"

["0.0.2-0.0.5"]
Calendar = "0.1-0.4"

["0.0.3"]
julia = "0.1-0.6"

["0.0.3-0.0.5"]
FactCheck = "0.1-0.4"

["0.0.4-0.0.5"]
julia = "0.2-0.6"

["0.0.6-0.1"]
julia = "0.3-0.6"

["0.0.6-0.2.0"]
Dates = "0.0-0.4"

["0.1-0.2.0"]
Compat = "0.0-0.44"

["0.1.2-0.3"]
URIParser = "0.0-0.3"

["0.2"]
julia = "0.4-0.6"

["0.2.5-0.2.7"]
Compat = "0.7.20-0.44"

["0.3"]
julia = "0.5-0.6"
