["0.0"]
Compat = "0.9-0.52"
DiffEqBase = "0.0-0.14"

["0.0-0.1"]
julia = "0.5-0.7"

["0.0-0.3"]
BinDeps = "0.4.3-0.8"
Parameters = "0.5-0.8"

["0.1"]
DiffEqBase = "0.15-2.10"

["0.1-0.3"]
Compat = "0.17-0.52"

["0.2"]
DiffEqBase = "1.5.1-2.10"

["0.2-0.3"]
julia = "0.6-0.7"

["0.3"]
DiffEqBase = "3.0-3.2"
