["0.1-0.3"]
Distributions = "0.1-0.14"
NLopt = "0.0-0.3"

["0.1.0"]
julia = "0.1-0.6"

["0.1.2"]
julia = "0.3-0.6"

["0.1.3-0.2.0"]
julia = "0.4"

["0.2.1"]
julia = "0.4-0.6"

["0.2.2-0.3"]
julia = "0.5-0.6"
