["0.1-0.3"]
julia = "0.3-0.6"
ArrayViews = "0.6"
Reexport = "0.0"

["0.1.0"]
EmpiricalRisks = "0.2.1-0.2.4"

["0.1.1"]
EmpiricalRisks = "0.2.2-0.2.4"

["0.1.1-0.3"]
Compat = "0.4.1-0.31"

["0.1.2-0.3"]
EmpiricalRisks = "0.2.3-0.2.4"
