["0.0-0.1"]
julia = "0.3-0.6"

["0.0.1"]
FactCheck = "0.0-0.4"

["0.1-0.2.5"]
BinDeps = "0.0-0.8"

["0.1-0.3"]
Homebrew = "0.0-0.6"

["0.1.5-0.2.5"]
Compat = "0.0-0.44"

["0.2"]
julia = "0.4-0.6"

["0.2.6-0.3"]
BinDeps = "0.4-0.8"
Compat = "0.9-0.44"

["0.3"]
julia = "0.5-0.6"
