["0.1-0.2"]
julia = "0.4-0.6"
Conda = "0.1-0.7"
PyPlot = "1.0-2.3"

["0.1-0.4"]
Anasol = "0.1-0.2"
BIGUQ = "0.1-0.3"
BlackBoxOptim = "0.0-0.3"
DataFrames = "0.1-0.10"
DataStructures = "0.2-0.7"
JLD = "0.5-0.8"
JSON = "0.1-0.15"
MetaProgTools = "0.1-0.2"
ProgressMeter = "0.0-0.5"
YAML = "0.1-0.2"

["0.1-0.4.4"]
Distributions = "0.1-0.14"

["0.1-0.4.9"]
Gadfly = "0.1-0.6"

["0.1-0.4.15"]
ODE = "0.1-0.7"

["0.1-0.4.17"]
ReusableFunctions = "0.1-0.2"

["0.1.0"]
NLopt = "0.0-0.3"

["0.1.0-0.1.2"]
Lora = "0.4.4-0.5"

["0.1.0-0.1.4"]
Sundials = "0.1-0.14"

["0.1.0-0.1.11"]
PyCall = "0.0-1.15"

["0.1.0-0.1.12"]
Optim = "0.1-0.4"

["0.1.0-0.1.14"]
ForwardDiff = "0.0-0.6"
HDF5 = "0.1-0.8"
LightXML = "0.1-0.5"

["0.1.1-0.2.3"]
Lexicon = "0.0-0.1"

["0.1.2-0.4"]
RobustPmap = "0.1-0.2"

["0.1.3-0.1.11"]
Lora = "0.5"

["0.1.5-0.2.3"]
Docile = "0.0-0.5"

["0.1.11"]
Ipopt = "0.1-0.2"
JuMP = "0.1-0.18"
NMF = "0.0-0.2"

["0.1.12"]
PyCall = "1.4-1.15"

["0.1.12-0.1.17"]
Lora = "0.3-0.5"

["0.1.13"]
Optim = "0.5-0.9"

["0.1.13-0.2"]
PyCall = "1.6.2-1.15"

["0.1.14-0.1.17"]
Optim = "0.1-0.9"

["0.1.18-0.2.3"]
Lora = "0.5"

["0.1.18-0.2.13"]
Optim = "0.5-0.9"

["0.1.18-0.4.11"]
StatsBase = "0.1-0.19"

["0.2.4-0.2.19"]
Documenter = "0.1-0.12"
Klara = "0.6-0.9"

["0.2.5-0.4"]
Images = "0.2-0.11"

["0.2.7-0.2.19"]
Compat = "0.7.15-0.33"

["0.2.14-0.4"]
AffineInvariantMCMC = "0.1-0.2"
Optim = "0.7-0.9"

["0.2.18-0.4"]
GeostatInversion = "0.1-0.2"

["0.3-0.4"]
julia = "0.5-0.6"
Conda = "0.4-0.7"
Documenter = "0.8.10-0.12"
PyCall = "1.8-1.15"
PyPlot = "2.2-2.3"

["0.3-0.4.12"]
Klara = "0.7-0.9"

["0.3.0"]
Compat = "0.12-0.33"

["0.3.1-0.4.9"]
Compat = "0.8-0.33"

["0.3.2-0.3.3"]
Ipopt = "0.2.6"

["0.3.2-0.4"]
Measures = "0.0-0.1"

["0.3.2-0.4.12"]
JuMP = "0.15-0.18"

["0.3.3"]
Colors = "0.4-0.8"

["0.3.3-0.4.12"]
MathProgBase = "0.5.10-0.6"

["0.3.6-0.4"]
NMF = "0.0-0.2"

["0.3.8-0.4.10"]
SVR = "0.1-0.2"

["0.4.5"]
Distributions = "0.12.5-0.14"

["0.4.6-0.4.28"]
Distributions = "0.1-0.14"

["0.4.7-0.4.28"]
DocumentFunction = "0.1"

["0.4.10-0.4.28"]
Compat = "0.13-0.33"
Compose = "0.5.2-0.5.4"
Gadfly = "0.6.2-0.6.4"

["0.4.11-0.4.28"]
SVR = "0.2.3-0.2.8"

["0.4.12-0.4.28"]
StatsBase = "0.15-0.19"

["0.4.13-0.4.28"]
JuMP = "0.17-0.18"
Klara = "0.8.6-0.9"
MathProgBase = "0.6.4"

["0.4.16-0.4.28"]
OrdinaryDiffEq = "0.0-2.19"

["0.4.18-0.4.28"]
ReusableFunctions = "0.2.6-0.2.9"

["0.4.28"]
Kriging = "0.0-0.1"
