["1.0"]
julia = "0.4-0.6"
Formatting = "0.1-0.3"
HttpCommon = "0.0-0.3"
JSON = "0.1-0.15"
LightXML = "0.1-0.5"

["1.0.0-1.0.1"]
Requests = "0.0-0.5"

["1.0.0-1.0.4"]
DataFrames = "0.1-0.10"

["1.0.2-1.0.6"]
Requests = "0.3.9-0.5"

["1.0.5-1.0.6"]
DataFrames = "0.7.3-0.10"
HttpParser = "0.2-0.3"
