["0.0"]
Sundials = "0.3-0.16"

["0.0-0.1.0"]
DiffEqBase = "0.0-0.6"
RecursiveArrayTools = "0.0-0.12"

["0.0-0.6"]
NLsolve = "0.7.3-0.13"
Ranges = "0.0"
RecipesBase = "0.1-0.2"

["0.0-1.4"]
Compat = "0.8.8-0.39"

["0.0-2.3.1"]
InplaceOps = "0.0.5-0.1"

["0.0-2.4"]
julia = "0.5-0.6"
DiffEqDiffTools = "0.0"
ForwardDiff = "0.2.4-0.4"

["0.0-2.31"]
GenericSVD = "0.0.2-0.1"
Parameters = "0.5-0.8"

["0.0.2-0.0.3"]
ParameterizedFunctions = "0.1-2.3"

["0.1.0"]
Juno = "0.1-0.3"

["0.1.1"]
DiffEqBase = "0.1.2-0.6"

["0.1.1-0.6"]
RecursiveArrayTools = "0.0.2-0.12"

["0.1.1-2.31"]
Juno = "0.2.5-0.3"

["0.2-0.5"]
DiffEqBase = "0.2-0.6"

["0.2-2.16"]
Calculus = "0.1.15-0.2"

["0.6"]
DiffEqBase = "0.4-0.6"

["1.0"]
DiffEqBase = "0.6-0.7"

["1.0-1.1"]
RecursiveArrayTools = "0.1.2-0.12"

["1.0-2.21"]
NLsolve = "0.9.1-0.13"

["1.0-2.31"]
DataStructures = "0.4.6-0.7"
Roots = "0.2.1-0.4"

["1.1"]
DiffEqBase = "0.7"

["1.1-2.4"]
Iterators = "0.1-0.3"

["1.2-1.3"]
DiffEqBase = "0.8-0.14"

["1.2-2.0.2"]
RecursiveArrayTools = "0.2-0.12"

["1.4-1.5"]
DiffEqBase = "0.11-0.14"

["1.5-2.0.1"]
Compat = "0.17-0.39"

["1.6-1.7"]
DiffEqBase = "0.13-0.14"

["1.8"]
DiffEqBase = "0.15-1.14"

["2.0.0-2.0.2"]
DiffEqBase = "1.1-1.14"

["2.0.2-2.31"]
Compat = "0.18-0.39"

["2.0.3-2.1"]
DiffEqBase = "1.3-1.14"

["2.0.3-2.2.0"]
RecursiveArrayTools = "0.6-0.12"

["2.2-2.5"]
DiffEqBase = "1.5-1.14"

["2.2.1-2.4"]
RecursiveArrayTools = "0.7.1-0.12"

["2.3-2.5"]
StaticArrays = "0.0-0.6"

["2.5-2.16"]
RecursiveArrayTools = "0.8-0.12"

["2.5-2.24"]
DiffEqDiffTools = "0.0.2"

["2.5-2.26"]
ForwardDiff = "0.5"

["2.5-2.31"]
julia = "0.6"

["2.6-2.7"]
DiffEqBase = "1.10-1.14"

["2.7-2.31"]
Reexport = "0.0"

["2.8-2.9"]
DiffEqBase = "1.11-1.14"

["2.10-2.11"]
DiffEqBase = "1.15"

["2.12-2.13"]
DiffEqBase = "1.16-1.18"
MuladdMacro = "0.0"

["2.14-2.18"]
DiffEqBase = "1.20-1.24"

["2.14-2.31"]
MuladdMacro = "0.0.2"
StaticArrays = "0.0-0.6"

["2.17-2.30"]
RecursiveArrayTools = "0.12"

["2.19"]
DiffEqBase = "1.23-1.24"

["2.20"]
DiffEqBase = "1.24.1"

["2.21-2.25"]
DiffEqBase = "2.0-2.6"

["2.22-2.31"]
NLsolve = "0.12.1-0.13"

["2.25-2.28"]
DiffEqDiffTools = "0.1"

["2.26-2.29"]
DiffEqBase = "2.4-2.6"

["2.27-2.31"]
ForwardDiff = "0.7"

["2.29-2.31"]
DiffEqDiffTools = "0.2"

["2.30-2.31"]
DiffEqBase = "2.6"

["2.31"]
RecursiveArrayTools = "0.13"
