["0.0-0.2"]
DiffEqBase = "0.0-2.10"

["0.0-0.4"]
julia = "0.5-0.7"

["0.1-1.1"]
RecursiveArrayTools = "0.0-0.14"

["0.3-0.7"]
DiffEqBase = "0.13-2.10"

["0.3.1-1.1"]
Compat = "0.19-0.53"

["0.4-0.6"]
Juno = "0.1-0.4"

["0.5-1.1"]
julia = "0.6-0.7"

["0.7-1.1"]
Requires = "0.1-0.4"

["1.0-1.1"]
DiffEqBase = "3.0-3.4"
