[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
RegistryCI = "0c95cc5f-2f7e-43fe-82dd-79dbcba86b32"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
GitHub = "5"
HTTP = "0.9, 1"
RegistryCI = "=8.4.1, 10"
TimeZones = "1"
julia = "1.3"
