["0.0"]
julia = "0.4-0.6"
SampledSignals = "0.0-0.2"
SIUnits = "0.0-0.1"

["0.0-1.0"]
BinDeps = "0.0-0.8"
FileIO = "0.0-0.6"
FixedPointNumbers = "0.0-0.4"
Homebrew = "0.0-0.6"

["1.0"]
julia = "0.6"
SampledSignals = "1.0-1.1"
