["0.0-0.1"]
Clustering = "0.2-0.9"
Compat = "0.0-0.31"
Distances = "0.1-0.5"
Distributions = "0.1-0.14"
MAT = "0.1-0.3"
MLBase = "0.1-0.7"
StatsBase = "0.1-0.19"

["0.0.1-0.0.4"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"

["0.0.1-0.0.5"]
julia = "0.3-0.6"

["0.0.5-0.1"]
ArrayViews = "0.1-0.6"
ProgressMeter = "0.0-0.4"

["0.0.6-0.1"]
julia = "0.4-0.6"
LegacyStrings = "0.1-0.2"
