["0.1-0.6"]
CodeTools = "53a63b46-67e4-5edd-8c66-0af0544a99b9"
Hiccup = "9fb69e20-1954-56bb-a84f-559cc56a8ff7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LNR = "7c4cb9fa-83a0-5386-9231-d6167c818060"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
Media = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"

["0.3-0.6"]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

["0.4.1-0.5.2"]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

["0.4.1-0.6"]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

["0.5-0.6.0"]
ASTInterpreter = "e6352adf-4ae3-5eb7-9a68-79830dcd0ac1"
Gallium = "87a02803-f0ee-5d26-846e-298423f06ab0"

["0.5.1-0.6"]
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"

["0.6.2-0.6.8"]
DocSeeker = "33d173f1-3be9-53c5-a697-8225b67db89c"

["0.6.3-0.6.8"]
ASTInterpreter2 = "e6d88f4b-b52a-544c-a8d3-7a4f12cb39c3"
