["0.0"]
julia = "0.4-0.6"

["0.0.1-0.0.3"]
PyCall = "0.0-1.15"

["0.0.2-0.0.3"]
BinDeps = "0.0-0.6"
Homebrew = "0.0-0.5"

["0.0.3"]
Compat = "0.0-0.33"

["0.0.4"]
BinDeps = "0.4-0.6"
Compat = "0.8-0.33"
Homebrew = "0.3-0.5"

["0.0.4-0.1"]
PyCall = "1.4-1.15"

["0.1"]
julia = "0.5-0.6"
LCMCore = "0.0"
