["0.0-0.3.1"]
MacroTools = "0.1-0.3"

["0.0-0.4"]
julia = "0.4-0.6"

["0.0.2-0.3"]
Requests = "0.0-0.5"

["0.1.1"]
DataStructures = "0.2-0.7"

["0.3.0"]
Compat = "0.0-0.31"

["0.3.1-0.4"]
Compat = "0.7.16-0.31"

["0.4-0.6"]
Requests = "0.3-0.5"

["0.5-0.9"]
julia = "0.5-0.6"

["0.5.1-0.9"]
Compat = "0.17-0.31"

["0.7-0.9"]
HTTP = "0.4"
JSON = "0.6-0.13"

["0.9"]
FixedPointDecimals = "0.0-0.1"
