["0.0-0.4"]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

["0.0-0.8"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

["0.1-0.4"]
DiffBase = "c5cfe0b6-c10a-51a5-87e3-fd79235949f0"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

["0.4-0.8"]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

["0.6.1-0.8"]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
