["0.0"]
PyCall = "1.4-1.15"
PyLCM = "0.0.3-0.1"

["0.0-0.1"]
julia = "0.5-0.6"
GeometryTypes = "0.1.6-0.4"
Meshing = "0.0.3-0.2"
Rotations = "0.2-0.6"
StaticArrays = "0.0.4-0.6"

["0.0-0.2"]
BinDeps = "0.4-0.8"
ColorTypes = "0.2-0.6"
CoordinateTransformations = "0.2-0.4"

["0.1"]
LCMCore = "0.0.2-0.0.4"

["0.1-0.2"]
DataStructures = "0.4-0.7"
JSON = "0.8-0.16"

["0.1.3"]
CMakeWrapper = "0.0-0.1"

["0.2"]
julia = "0.6"
CMakeWrapper = "0.0.2-0.1"
GeometryTypes = "0.4"
LCMCore = "0.0.4"
Meshing = "0.2"
Rotations = "0.5-0.6"
StaticArrays = "0.5-0.6"
