["0.0-0.2"]
Iterators = "0.1-0.3"

["0.0.1-0.0.2"]
julia = "0.2-0.6"
Distance = "0.2-0.5"

["0.0.3-0.0.7"]
julia = "0.3-0.6"

["0.0.3-0.3"]
Distances = "0.1-0.5"

["0.0.4-0.0.6"]
Compat = "0.0-0.31"

["0.0.7-0.1"]
Compat = "0.8.4-0.31"

["0.1"]
julia = "0.4-0.6"

["0.2-0.3"]
julia = "0.5-0.6"
Compat = "0.17-0.31"

["0.3"]
IterTools = "0.1"
