["0.1-0.2"]
JSON = "0.1-0.5"

["0.1-0.4"]
julia = "0.4-0.7"

["0.1-0.7"]
DataFrames = "0.1-0.10"

["0.1-0.9"]
Blink = "0.3.3-0.6"
Colors = "0.4-0.8"

["0.3"]
Compat = "0.7.16-0.49"

["0.3.0-0.3.1"]
JSON = "0.6-0.8"

["0.3.2-0.9"]
JSON = "0.7-0.16"
LaTeXStrings = "0.1-0.3"

["0.4-0.6.2"]
Compat = "0.8.4-0.49"

["0.4-0.9"]
DocStringExtensions = "0.1-0.4"

["0.5-0.6"]
julia = "0.5-0.7"

["0.5-0.7"]
Juno = "0.1-0.3"

["0.6.3-0.6.5"]
Compat = "0.18-0.49"

["0.7-0.9"]
julia = "0.6-0.7"

["0.8-0.9"]
Requires = "0.1-0.4"
