["0.0-0.1"]
DiffEqDiffTools = "0.0.2"

["0.0-0.3"]
DiffEqBase = "0.0-2.10"
NLsolve = "0.1-0.13"

["0.0-1.0"]
julia = "0.6-0.7"
BandedMatrices = "0.0-0.3"
Reexport = "0.0-0.1"

["0.2"]
DiffEqDiffTools = "0.1"

["0.3"]
DiffEqDiffTools = "0.2"

["1.0"]
DiffEqBase = "0.0-3.4"
DiffEqDiffTools = "0.2-0.3"
NLsolve = "0.14-1.0"
