["0.1-0.2.1"]
julia = "0.1-0.7"

["0.2.2-0.3.1"]
julia = "0.2-0.7"

["0.3.2-0.3.19"]
julia = "0.3-0.7"

["0.3.18-0.3.19"]
Compat = "0.0-0.52"

["0.4-0.5"]
julia = "0.4-0.7"

["0.5.2-0.5.10"]
Compat = "0.7.13-0.52"

["0.6"]
julia = "0.5-0.7"

["0.6.2-0.6.4"]
Compat = "0.18-0.52"

["0.7"]
julia = "0.6-0.7"
