["0.0"]
julia = "0.2-0.3"
Lumberjack = "0.0-2.1"
Requests = "0.0-0.5"

["0.1"]
julia = "0.5-0.7"

["0.1-0.2"]
HttpCommon = "0.2.4-0.4"
Memento = "0.1.1-0.5"
Requests = "0.4-0.5"

["0.2"]
julia = "0.6-0.7"
