["0.0-0.3"]
Calculus = "0.1-0.2"
Distributions = "0.1-0.15"

["0.0.1"]
julia = "0.2-0.7"
Optim = "0.1-0.4"

["0.0.2"]
julia = "0.3-0.7"
Optim = "0.1-0.13"

["0.1-0.2"]
julia = "0.4-0.7"

["0.1.0"]
Optim = "0.6-0.13"

["0.1.1"]
Optim = "0.7-0.13"

["0.2"]
Optim = "0.7.5-0.13"

["0.2-0.3"]
Compat = "0.9.1-0.53"

["0.3"]
julia = "0.5-0.7"
OptimBase = "0.1-1.0"
