["0.0"]
julia = "0.3-0.6"

["0.0.1"]
DataFrames = "0.5.6-0.10"
StatsBase = "0.5.3-0.19"

["0.1-0.2.0"]
Compat = "0.0-0.39"

["0.1-0.3"]
Gadfly = "0.1-0.6"
Mamba = "0.3-0.11"

["0.1.0-0.1.2"]
julia = "0.3"

["0.1.3-0.2.0"]
julia = "0.3-0.6"

["0.2.1"]
julia = "0.4-0.6"

["0.3.0-0.3.1"]
julia = "0.4"

["0.3.2"]
julia = "0.4-0.6"
BinDeps = "0.0-0.8"

["0.3.2-1.0"]
Homebrew = "0.0-0.6"

["1.0"]
Gadfly = "0.4.3-0.6"

["1.0-1.1"]
Mamba = "0.10-0.11"

["1.0-2.0"]
julia = "0.5-0.6"
BinDeps = "0.4.3-0.8"

["1.1"]
Gadfly = "0.5.2-0.6"

["1.1-2.0"]
Homebrew = "0.4-0.6"

["2.0"]
Compat = "0.17-0.39"
Documenter = "0.10-0.12"
