["0.1-0.2"]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
POMDPToolbox = "0729bffe-8e6b-52fa-a3fa-893719b744f4"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

["0.1.2-0.2"]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"

["0.1.3-0.2"]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
