["0.0-0.7"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

["0.0.1-0.0.2"]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

["0.1-0.7"]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

["0.2-0.6"]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

["0.2-0.7"]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

["0.6-0.7"]
PenaltyFunctions = "06bb1623-fdd5-5ca2-a01c-88eae3ea319e"
