["0.0-0.1"]
julia = "0.6-0.7"
Requests = "0.5"

["0.0.4"]
DataFrames = "0.1-0.10"

["0.0.5-0.0.6"]
DataFrames = "0.10"

["0.0.5-0.1"]
CSV = "0.1-0.2"

["0.0.7"]
DataFrames = "0.10-0.11"

["0.1.1-0.1.2"]
DataFrames = "0.10"

["0.1.3-0.1.5"]
DataFrames = "0.10-0.11"
