["0.1-0.2"]
DiffEqBase = "0.0-2.10"

["0.1-0.2.0"]
julia = "0.2-0.7"

["0.1.0-0.1.1"]
Polynomial = "0.1"

["0.1.2-0.7"]
Polynomials = "0.0-0.2"

["0.2.1"]
julia = "0.3-0.7"
Compat = "0.4.1-0.49"

["0.3"]
DiffEqBase = "0.0-0.14"

["0.3-0.5"]
Compat = "0.9-0.49"

["0.3-0.7"]
julia = "0.5-0.7"

["0.4"]
DiffEqBase = "0.15-2.10"

["0.5"]
DiffEqBase = "1.0-2.10"

["0.6-0.7"]
Compat = "0.17-0.49"
DiffEqBase = "1.5.1-2.10"

["0.7"]
Reexport = "0.0-0.1"
