["0.0"]
julia = "0.3-0.6"
Docile = "0.0-0.5"
MathProgBase = "0.3"

["0.1-0.2"]
julia = "0.4-0.6"

["0.1.0"]
MathProgBase = "0.4"

["0.1.1"]
MathProgBase = "0.5"

["0.2-0.3.0"]
MathProgBase = "0.5-0.6"

["0.3"]
julia = "0.5-0.6"

["0.3.1"]
MathProgBase = "0.5-0.7"
