["0.0"]
julia = "0.3-0.7"

["0.0-0.1"]
MathProgBase = "0.3.8-0.3.19"

["0.0-0.3"]
BinDeps = "0.0-0.8"
Homebrew = "0.0-0.6"

["0.0.2-0.1.1"]
Compat = "0.0-0.52"

["0.1-0.2"]
julia = "0.4-0.7"

["0.2.0-0.2.1"]
MathProgBase = "0.4"

["0.2.2-0.2.6"]
MathProgBase = "0.5"

["0.2.5-0.2.8"]
Compat = "0.8.6-0.52"

["0.2.7"]
MathProgBase = "0.5-0.6"

["0.2.8"]
MathProgBase = "0.5"

["0.3"]
julia = "0.5-0.7"

["0.3.0-0.3.2"]
MathProgBase = "0.5-0.6"

["0.3.3"]
MathProgBase = "0.5-0.7"
