["0.0.1"]
julia = "0.1-0.6"

["0.0.2-0.0.5"]
julia = "0.2-0.6"

["0.0.6"]
Compat = "0.0-0.31"

["0.0.6-0.1"]
julia = "0.3-0.6"

["0.1.2-0.2"]
Compat = "0.0-0.31"

["0.2"]
julia = "0.4-0.6"

["0.3"]
julia = "0.5-0.6"
Compat = "0.8-0.31"
