["0.0"]
HttpCommon = "0.0-0.3"

["0.0-0.2"]
julia = "0.3-0.6"
Nettle = "0.1-0.3"

["0.0-0.5"]
Requests = "0.0-0.5"

["0.0.3-0.4"]
Compat = "0.0-0.44"

["0.1-0.5"]
URIParser = "0.0-0.3"

["0.2-0.6"]
FactCheck = "0.0-0.4"

["0.3-0.4"]
julia = "0.4-0.6"

["0.3-0.6"]
Nettle = "0.2-0.3"

["0.5-0.6"]
julia = "0.6"

["0.6"]
HTTP = "0.0-0.5"
