["0.0-0.1"]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

["0.0-0.9"]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"

["0.4-0.9"]
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

["0.8-0.9"]
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
