["0.0"]
julia = "0.1-0.6"

["0.1-0.3.5"]
julia = "0.2-0.6"

["0.3.6-0.7.0"]
julia = "0.3-0.6"

["0.7.1-0.7.2"]
julia = "0.4-0.6"

["0.7.3-0.7.4"]
julia = "0.3-0.6"

["0.7.5"]
julia = "0.4-0.6"

["0.7.6-0.7.14"]
julia = "0.3-0.6"

["0.7.15"]
julia = "0.5-0.6"

["0.7.16-0.8"]
julia = "0.3-0.6"

["0.9-0.26"]
julia = "0.4-0.6"

["0.27-0.31"]
julia = "0.5-0.6"
