["0.1.0-0.1.1"]
GLPK = "0.2-0.4"
MathProgBase = "0.1-0.2"

["0.1.0-0.1.14"]
julia = "0.2-0.6"

["0.1.2"]
MathProgBase = "0.1.2-0.2"

["0.1.2-0.3"]
GLPK = "0.2.8-0.4"

["0.1.3"]
MathProgBase = "0.1.5-0.2"

["0.1.4"]
MathProgBase = "0.1.6-0.2"

["0.1.5"]
MathProgBase = "0.1.5-0.2"

["0.1.6-0.1.16"]
MathProgBase = "0.3"

["0.1.14"]
Compat = "0.3.5-0.33"

["0.1.15-0.1.16"]
julia = "0.3-0.6"
Compat = "0.7.1-0.33"

["0.2"]
julia = "0.4-0.6"

["0.2.0-0.2.1"]
MathProgBase = "0.4"

["0.2.2"]
MathProgBase = "0.5"

["0.2.3-0.3"]
MathProgBase = "0.5-0.6"

["0.3"]
julia = "0.5-0.6"

["0.3.4"]
Compat = "0.17-0.33"
