["0.1-1.0.5"]
julia = "0.2-0.6"

["0.1-1.2"]
BinDeps = "0.0-0.8"

["1.0.2-1.0.8"]
Compat = "0.2-0.39"

["1.0.6-1.1"]
julia = "0.3-0.6"

["1.0.9-1.1"]
Compat = "0.7-0.39"

["1.2"]
julia = "0.4-0.6"
Compat = "0.8-0.39"
