["0.0"]
DiffEqBase = "0.0-2.10"

["0.0-0.1"]
julia = "0.5-0.7"

["0.0-0.2"]
DataStructures = "0.2-0.7"
PyCall = "0.0-1.15"

["0.0.2-0.1.1"]
Conda = "0.1-0.7"

["0.1"]
DiffEqBase = "0.11-2.10"

["0.1-0.2"]
RecipesBase = "0.0-0.3"

["0.1.2-0.2"]
Conda = "0.2-0.7"

["0.2"]
julia = "0.6-0.7"
DiffEqBase = "3.0-3.2"
