["0.1-0.5"]
julia = "0.2-0.6"

["0.3-0.7"]
BinDeps = "0.0-0.8"

["0.5.2"]
Compat = "0.0-0.39"

["0.6-0.8"]
julia = "0.3-0.6"

["0.6-0.8.3"]
Compat = "0.4.1-0.39"

["0.8-0.11"]
BinDeps = "0.3.12-0.8"

["0.8.4"]
Compat = "0.8.6-0.39"

["0.9"]
Compat = "0.9.5-0.39"

["0.9-0.10"]
julia = "0.4-0.6"

["0.10"]
Compat = "0.17-0.39"

["0.11"]
julia = "0.5-0.6"
Compat = "0.29-0.39"
Homebrew = "0.0-0.6"
