["0.1-0.2"]
julia = "0.4-0.6"

["0.1-0.3"]
QuantEcon = "0.0-0.14"

["0.2-0.3"]
Reexport = "0.0"

["0.2.0"]
BasisMatrices = "0.1-0.2"

["0.2.1"]
BasisMatrices = "0.2"

["0.3"]
julia = "0.5-0.6"
BasisMatrices = "0.3-0.4"
