["0.0"]
julia = "0.4-0.6"
AWSCore = "0.0-0.3"

["0.1"]
AWSCore = "0.1-0.3"

["0.1-0.2"]
julia = "0.5-0.6"

["0.1-0.3"]
Retry = "0.0-0.1"
SymDict = "0.0-0.1"

["0.2"]
AWSCore = "0.2-0.3"

["0.3"]
julia = "0.6"
AWSCore = "0.3"
