["0.1"]
julia = "0.2-0.7"

["0.1-0.3"]
DiffEqBase = "0.0-2.10"

["0.1.0-0.1.2"]
BinDeps = "0.0-0.8"

["0.1.3-0.2"]
BinDeps = "0.3-0.8"

["0.2-0.3"]
julia = "0.4-0.7"

["0.2.1-0.2.2"]
Compat = "0.0-0.49"

["0.3-0.11.0"]
Compat = "0.9-0.49"

["0.3-0.19"]
BinDeps = "0.4.3-0.8"

["0.4"]
DiffEqBase = "0.0-0.1"

["0.4-0.14"]
julia = "0.5-0.7"

["0.5-0.9"]
DiffEqBase = "0.2-0.14"

["0.10"]
DiffEqBase = "0.15-2.10"

["0.11-0.12"]
DiffEqBase = "1.0-2.10"

["0.11.1-0.15"]
Compat = "0.17-0.49"

["0.13-0.18"]
DiffEqBase = "1.5.1-2.10"

["0.14.3-1.0"]
Reexport = "0.0-0.1"

["0.15-1.0"]
julia = "0.6-0.7"

["0.17-1.0"]
DataStructures = "0.2-0.7"
Roots = "0.1-0.5"

["0.19"]
DiffEqBase = "2.8-2.10"

["1.0"]
BinaryProvider = "0.1"

["1.0.0"]
DiffEqBase = "2.10"

["1.0.1"]
DiffEqBase = "2.10-3.0"
