["1.0-1.1"]
julia = "0.3-0.7"
Color = "0.2.10-0.4"

["1.0-1.2"]
Cairo = "0.0-0.5"
DataFrames = "0.1-0.10"

["1.1"]
Lexicon = "0.0-0.1"

["1.1-1.2"]
StatsBase = "0.1-0.20"

["1.2"]
julia = "0.4-0.7"
Colors = "0.4-0.8"
