["0.0-0.1"]
julia = "0.3-0.7"

["0.0.1"]
ECOS = "0.1-0.8"
MathProgBase = "0.3.1-0.3.19"

["0.0.2"]
ECOS = "0.4.1-0.8"

["0.0.2-0.1"]
MathProgBase = "0.3.8-0.3.19"

["0.0.5-0.1"]
Compat = "0.4.4-0.52"

["0.1-0.5"]
DataStructures = "0.2-0.7"

["0.2"]
MathProgBase = "0.4"

["0.2-0.4"]
julia = "0.4-0.7"

["0.3"]
MathProgBase = "0.5"

["0.4"]
MathProgBase = "0.5-0.6"

["0.5"]
julia = "0.5-0.7"
MathProgBase = "0.5-0.7"
