["0.0-0.2"]
julia = "0.5-0.7"

["0.0-0.5"]
DiffEqDiffTools = "0.0-0.2"

["0.0.1"]
DiffEqBase = "0.0-0.14"

["0.0.2"]
DiffEqBase = "0.1.2-0.14"

["0.0.3-0.0.4"]
DiffEqBase = "0.2-0.14"

["0.1"]
DiffEqBase = "0.15"

["0.2-0.5"]
DiffEqBase = "0.15-2.10"

["0.2.2-1.0"]
Compat = "0.17-0.53"

["0.3-1.0"]
julia = "0.6-0.7"

["0.4-1.0"]
ForwardDiff = "0.0-0.7"

["0.5-1.0"]
DiffEqCallbacks = "0.0-1.0"
QuadGK = "0.1-0.2"

["1.0"]
DiffEqBase = "3.0-3.4"
DiffEqDiffTools = "0.3"
