["0.0"]
julia = "0.5-0.6"
Compat = "0.19-0.37"
NullableArrays = "0.1"
Reexport = "0.0"
SortingAlgorithms = "0.0-0.2"
StatsBase = "0.11-0.19"

["0.0.1"]
Juno = "0.2.4-0.3"

["0.0.1-0.0.2"]
CategoricalArrays = "0.0.6-0.1"
DataStreams = "0.0-0.1"
FileIO = "0.1.2-0.6"
GZip = "0.1-0.3"

["0.0.3"]
CategoricalArrays = "0.1.2-0.1.6"
DataStreams = "0.1"
WeakRefStrings = "0.1.3-0.4"
