name: registrator_issues
on:
  issues:
    types: [opened, reopened]
jobs:
  registrator_issues:
    runs-on: ubuntu-latest
    steps:
      - run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url = "https://github.com/JuliaRegistries/RegistratorServerless.jl.git", rev = "master"))'
      - run: julia  -e 'using RegistratorServerless; user = "${{ github.actor }}"; issue_title = "${{ github.event.issue.title }}"; @info("", issue_title, user)'
        env:
          REGISTRATOR_GITHUB_TOKEN: ${{ secrets.DILUMALUTHGEBOT_TOKEN }}
          REGISTRATOR_REGISTRY: 'JuliaRegistries/General'
          REGISTRATOR_SERVERLESS_REPO: 'JuliaRegistries/General'
