name: remember_to_update_registryci

on:
  schedule:
    - cron: '00 * * * *'
  workflow_dispatch:

jobs:
  remember_to_update_registryci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.5.2'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819 # v1.0.0
      - uses: julia-actions/setup-julia@d622e3db7bb58726d23ba936dc11fd9986e1ccfc # v1.2.2
        with:
          version: ${{ matrix.version }}
      - name: Install dependencies
        run: julia -e 'import Pkg; Pkg.add(["GitCommand", "GitHub", "Pkg"])'
      - name: Update .ci/Manifest.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'include(".ci/remember_to_update_registryci.jl"); "${{ github.repository }}" == "JuliaRegistries/General" && RememberToUpdateRegistryCI.main(".ci"; registry = "${{ github.repository }}", cc_usernames = String[])'
