name: "Close stale pull requests"
on:
  schedule:
    - cron: "16 12 * * *"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This pull request has been inactive for 30 days and will be automatically closed 7 days from now. If this pull request should not be closed, please either (1) fix the AutoMerge issues and re-trigger Registrator, which will automatically update the pull request, or (2) post a comment explaining why you would like this pull request to be manually merged. [noblock]'
        close-pr-message: 'This pull request has been inactive for more than 30 days and has automatically been closed. Feel free to register your package or version again once you fix the AutoMerge issues. [noblock]'
        days-before-issue-stale: -1
        days-before-pr-stale: 30
        days-before-issue-close: -1
        days-before-pr-close: 7
        delete-branch: true
        operations-per-run: 100
