["0.1"]
DataFrames = "0.1-0.10"

["0.1-0.2.1"]
julia = "0.1-0.7"

["0.2.2-0.2.3"]
julia = "0.3-0.7"
Docile = "0.0-0.5"

["0.2.2-0.2.8"]
DataFrames = "0.1-0.10"

["0.2.4"]
julia = "0.4-0.7"

["0.2.4-0.2.8"]
Docile = "0.3.1-0.5"
Lexicon = "0.0-0.1"

["0.2.5"]
Compat = "0.0-0.53"

["0.2.5-0.2.8"]
julia = "0.3-0.7"

["0.2.6-0.2.8"]
Compat = "0.7.9-0.53"

["0.3"]
julia = "0.5-0.7"
Compat = "0.18-0.53"
DataFrames = "0.9-0.10"

["0.4"]
julia = "0.6-0.7"
DataFrames = "0.9-0.11"
Phylo = "0.2"

["0.4.1-0.4.2"]
Missings = "0.2"

["0.4.2"]
Compat = "0.47-0.53"
